name: Dune Weaver Mini Pro (28BYJ-48 )
meta: By Tuan Nguyen (2025-12-24)
board: ESP32
kinematics: {}
stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 10
  disable_delay_us: 0
axes:
  x:
    steps_per_mm: 256
    max_rate_mm_per_min: 200
    acceleration_mm_per_sec2: 10
    max_travel_mm: 4000
    motor0:
      hard_limits: false
      unipolar:
        phase0_pin: gpio.13
        phase1_pin: gpio.12
        phase2_pin: gpio.14
        phase3_pin: gpio.27
        half_step: false
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
  y:
    steps_per_mm: 210
    max_rate_mm_per_min: 200
    acceleration_mm_per_sec2: 10
    max_travel_mm: 6.25
    motor0:
      hard_limits: false
      unipolar:
        phase0_pin: gpio.19
        phase1_pin: gpio.18
        phase2_pin: gpio.5
        phase3_pin: gpio.21
        half_step: false
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
uart1:
  txd_pin: gpio.1
  rxd_pin: gpio.3
  baud: 115200
  mode: 8N1
uart_channel1:
  uart_num: 1